name: Call Replace Tag

on:
  push:
    paths:
      - 'sample.txt'

permissions:
  contents: write
  packages: write

jobs:
  call-replace-tag:
    uses: ./.github/workflows/replace-tag-reusable.yml
    with:
      file: 'sample.txt'