name: Replace Tag Reusable Workflow

on: 
  #workflow_dispatch:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

# permissions:
#   contents: write
#   packages: write

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace tag in file
        uses: ./.github/actions/replace-tag
        with:
          file: ${{ inputs.file }}

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ inputs.file }}
          git commit -m "Update tag from 1 to 2" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create and push docker image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$REPO_LOWER/replace-tag
          COMMIT_HASH=$(git rev-parse --short HEAD)

          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:$COMMIT_HASH .

          echo "Logging in to ghcr.io"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          echo "Pushing Docker image to GHCR..."
          docker push $IMAGE_NAME:$COMMIT_HASH
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}