name: Replace Tag Reusable Workflow

on: 
  workflow_dispatch:
    inputs:
      file:
        required: true
        type: string

permissions:
  contents: write

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace tag in file
        uses: ./.github/actions/replace-tag
        with:
          file: ${{ inputs.file }}

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ inputs.file }}
          git commit -m "Update tag from 1 to 2" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
